apps/belt_review/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^$', views.index),
    url(r'^register$', views.register),
    url(r'^login$', views.login),
    url(r'^home$', views.home),
    url(r'^logout$', views.logout),
    url(r'^add$', views.add),
    url(r'^add_book$', views.add_book),
    url(r'^books/(?P<book_id>\d+)$', views.books, name="books_page"),

    url(r'^users/(?P<review_user_id>\d+)$', views.users),

    url(r'^add_review/(?P<book_id>\d+)$', views.add_review),
    url(r'^delete/(?P<review_id>\d+)$', views.delete),

]



# urlpatterns = [
#     url(r'^$', views.index),
#     url(r'^process_course$', views.process_course),
#     # url(r'^comment_show$', views.comment_show),
#     url(r'^delete/(?P<course_id>\d+)$', views.delete),
#     url(r'^final/(?P<course_id>\d+)$', views.final),
#     url(r'^edit/(?P<course_id>\d+)$', views.edit),
#     url(r'^edit_final/(?P<course_id>\d+)$', views.edit_final),
    # url(r'^comment/(?P<course_id>\d+)$', views.comment, name="comments_page"),
    # url(r'^comment_process/(?P<course_id>\d+)$', views.comment_process),

belt_review_assignment/urls.py
from django.conf.urls import url, include
# from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.belt_review.urls')),
]

apps/belt_review/models.py
from __future__ import unicode_literals
import re
EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
from django.db import models
import bcrypt
# Create your models here.
class UserManager(models.Manager):
    def login(self, post):
        user_list = User.objects.filter(email=post['email'])
        if user_list:
            user = user_list[0]
            #check their credentials
            if bcrypt.hashpw(post['password'].encode(), user.password.encode()) == user.password:
                #then login is valid
                return user
        #else:
        return None

    def register(self, post):
        encrypted_password = bcrypt.hashpw(post['password'].encode(), bcrypt.gensalt())
        User.objects.create(name=post['name'], alias=post['alias'], email=post['email'], password=encrypted_password)

    def validate_user_info(self, post):
        errors = []

        if len(post['name']) < 3:
            errors.append('Name must contain at least 3 characters!')
        # if not post['firstname'].isalpha():
        #     errors.append('All First Name characters must be alphabetic!.')
        if len(post['alias']) == 0:
            errors.append('Alias cannot be blank!')

        if len(post['password']) < 8:
            errors.append('Your password must contain at least 8 characters!')
        if post['password'] != post['confpass']:
            errors.append('Your confirmation password must match your password!')

    	if not EMAIL_REGEX.match(post['email']):
            errors.append('Please enter a valid email address!')
        if len(User.objects.filter(email=post['email'])) > 0:
            errors.append("That Email address is unavailable!")

        return errors

class AuthorManager(models.Manager):
    pass
class BookManager(models.Manager):
    pass
class ReviewManager(models.Manager):
    pass

class User(models.Model):
    name = models.CharField(max_length=100)
    alias = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    password = models.CharField(max_length=250)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    objects = UserManager()

class Author(models.Model):
    name = models.CharField(max_length=250)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    objects = AuthorManager()

class Book(models.Model):
    author = models.ForeignKey(Author)
    title = models.CharField(max_length=250)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    objects = BookManager()

class Review(models.Model):
    user = models.ForeignKey(User)
    book = models.ForeignKey(Book)
    review = models.CharField(max_length=1000)
    rating = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    objects = ReviewManager()

apps/belt_review/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib import messages
from .models import User, Book, Review, Author
# Create your views here.
def index(request):
    return render(request, "belt_review/index.html")

def login(request):
    #either they're good at logging in or not
    if request.method == "POST":
        user = User.objects.login(request.POST)
        if not user:
            messages.error(request, "Invalid login credentials!")
        else:
            request.session['logged_user'] = user.id
            # don't need this, unless I'm calling for messages on my "home" page, but I shouldn't because I just have a welcome {{__ }} thang. : messages.success(request, "Welcome {}!".format(user.alias))
            return redirect('/home')
    return redirect('/')

def register(request):
    if request.method == "POST":
        form_errors = User.objects.validate_user_info(request.POST)

    #if there are errors, throw them into flash:
        if len(form_errors) > 0:
            for error in form_errors:
                messages.error(request, error)
        else:
            #register User
            User.objects.register(request.POST)
            messages.success(request, "You have Successfully registered! Please sign-in to continue")

    return redirect('/')

def home(request):
    if "logged_user" not in request.session:
        messages.error(request, "Gotta login bro")
        return redirect('/')
    books = Book.objects.all()
    # review = Review.objects.all()
    review = Review.objects.all().order_by("-id")[:3]

    context = {
        'user' : User.objects.get(id=request.session['logged_user']),
        'books': books,
        'review': review
    }
    return render(request, "belt_review/home.html", context)

def add(request):
    if "logged_user" not in request.session:
        messages.error(request, "Gotta login bro")
        return redirect('/')
    authors = Author.objects.all()
    print authors
    context = {}
    if authors:
        context = {
            "authors": authors
        }
    return render(request, "belt_review/add.html", context)

def add_book(request):
    if "logged_user" not in request.session:
        messages.error(request, "Gotta login bro")
        return redirect('/')
    if request.method == "POST":
        if request.POST['newauthor'] != "":
            print "we want to add an author"
            user = User.objects.get(id=request.session['logged_user'])
            author = Author.objects.create(name=request.POST['newauthor'])
            book = Book.objects.create(title=request.POST['title'], author=author)
            Review.objects.create(user=user, review=request.POST['review'], rating=request.POST['rating'], book=book)

        elif request.POST['author'] != "":
            print "we want to use a author already inside the db"
            user = User.objects.get(id=request.session['logged_user'])
            author = Author.objects.get(id=request.POST['author'])
            book = Book.objects.create(title=request.POST['title'], author=author)
            Review.objects.create(user=user, review=request.POST['review'], rating=request.POST['rating'], book=book)

        if request.POST['newauthor'] == "" and request.POST['author'] == "":
            messages.add_message(request, messages.WARNING, "Please add/select an Author")

        context = {
            "book": book
        }

        return redirect('books_page', book_id=book.id)

def books(request, book_id):
    if "logged_user" not in request.session:
        messages.error(request, "Gotta login bro")
        return redirect('/')
    logged_user = User.objects.get(id=request.session['logged_user'])
    # user = User.objects.get(id=book_id)
    book = Book.objects.get(id=book_id)
    reviews = Review.objects.filter(book_id=book_id)

    context = {
        "book": book,
        "reviews": reviews,
        "logged_user": logged_user,
        # "user": user
    }
    return render(request, "belt_review/books.html", context)

def add_review(request, book_id):
    if "logged_user" not in request.session:
        messages.error(request, "Gotta login bro")
        return redirect('/')
    if request.method == "POST":
        book = Book.objects.get(id=book_id)
        user = User.objects.get(id=request.session['logged_user'])

        Review.objects.create(rating=request.POST['rating'], review=request.POST['review'], book=book, user=user)


    return redirect('books_page', book_id=book_id)



def users(request, review_user_id):
    if "logged_user" not in request.session:
        messages.error(request, "Gotta login bro")
        return redirect('/')
    # logged_user = User.objects.get(id=request.session['logged_user'])
    user = User.objects.get(id=review_user_id)
    review_book_titles = Review.objects.filter(book_id=review_user_id)

    rating = Review.objects.filter(user_id=review_user_id)

    if rating > 0:
        rating = len(rating)

    # rating = Review.objects.filter(book_id=review_user_id)

    # books = Book.objects.all()
    # review = Review.objects.filter(user_id=user_id)
    #
    context = {
        "user": user,
        "review": review_book_titles,
        "rating": rating


    #     "logged_user": logged_user,
    }
    return render(request, "belt_review/users.html", context)

def delete(request, review_id):
    if "logged_user" not in request.session:
        messages.error(request, "Gotta login bro")
        return redirect('/')

    review = Review.objects.get(id=review_id)
    book_id = review.book.id

    #delete query
    review.delete()

    return redirect('books_page', book_id=book_id)


def logout(request):
    if 'logged_user' in request.session:
        request.session.pop('logged_user')
    return redirect('/')

apps/belt_review/templates/belt_review/add.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Add Book and Review</title>
  </head>
  <body>
    <a href="/home"><button>Home</button></a>
    <a href="/logout"><button>Logout</button></a>

    <h2>Add a New Book Title and a Review:</h2>
    {% if messages %}
      {% for message in messages %}
        <p{% if message.tags %} class="{{ message.tags }}"{% endif %}> {{message}}</p>
      {% endfor %}
    {% endif %}

    <div class="addbook">
      <form action="/add_book" method="post">
        {% csrf_token %}
        <h4>Book Title:<input type="text" name="title"></h4>

        <h4>Author:</h4>
          <p>Choose from the list:<select name="author">
              <option default value = "">Choose an Author</option>
              {% for author in authors %}
              <option value="{{author.id}}">{{author.name}}</option>
              {% endfor %}

          </select></p>
          <p>Or add a new author:<input type="text" name="newauthor"></p>

        <h4>Review:<input type="textarea" name="review"></h4>
        <h4>Rating:
          <select name="rating">
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
            <option value="5">5</option>
          </select>
        </h4>
        <input type="submit" value="Add a Book and Review">
      </form>

    </div>
  </body>
</html>

apps/belt_review/templates/belt_review/books.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Book</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'belt_review/css/styles.css' %}"media="screen" title="no title"  charset="utf-8">
  </head>
  <body>
    <a href="/home"><button>Home</button></a>
    <a href="/logout"><button>Logout</button></a>
    <h1>{{book.title}}</h1>
    <h4>Author: {{book.author.name}}</h4>
    <div class="reviews">
      <h4>Reviews:</h4>
      <hr>
      {% for review in reviews %}
      <p>Rating: {{review.rating}} star(s)</p>
        <a href="/users/{{review.user.id}}">{{review.user.alias}}</a>

         says {{review.review}}
      <p>Posted: {{review.created_at}}</p>
        {% if review.user == logged_user%}
        <a href="/delete/{{review.id}}"><button id="delete">Delete this Review</button></a>
        {% endif %}
      <hr>
      {% endfor %}






    </div>
    <div class="addreview">
      <h3>Add a Review:</h3>
      <form action="/add_review/{{book.id}}" method="post">
        {% csrf_token %}
        <textarea name="review"></textarea>
          Rating: <select name="rating">
          <option value="1">1</option>
          <option value="2">2</option>
          <option value="3">3</option>
          <option value="4">4</option>
          <option value="5">5</option>
        </select>
        <input type="submit" value="Submit Review">
      </form>




    </div>

  </body>
</html>

apps/belt_review/templates/belt_review/home.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Home Page</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'belt_review/css/styles.css' %}"media="screen" title="no title"  charset="utf-8">
  </head>
  <body>
    <div class="header">
      <a href="/add"><button>Add Book and Review</button></a>
      <a href="/logout"><button>Logout</button></a>
      <h1>Welcome, {{user.alias}}!</h1>
    </div>
    <div class="left">
      <h2>Recent Book reviews:</h2>

      {% for review in review %}
      <h4><a href="/books/{{review.book.id}}">{{review.book.title}}</a></h4>
      <p>Rating: {{review.rating}} star(s)</p>
      <p><a href="/users/{{review.user.id}}">{{review.user.alias}}</a> says: {{review.review}}</p>
      <p>Posted: {{review.created_at}}</p>
      <hr>
      {% endfor %}

      <!-- show latest three -->
    </div>
    <div class="right">
      <h2>Other Books with Reviews:</h2>

      {% for book in books %}
      <p><a href="/books/{{book.id}}">{{book.title}}</a></p>
      {% endfor %}


    </div>




  </body>

</html>

apps/belt_review/templates/belt_review/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Belt Review</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'belt_review/css/styles.css' %}"media="screen" title="no title"  charset="utf-8">
  </head>
  <body>
    <h1>Welcome!</h1>
    <!-- {% if messages %}
      {% for message in messages %}
        <p{% if message.tags %} class="{{ message.tags }}"{% endif %}> {{message}}</p>
      {% endfor %}
    {% endif %} -->
      {% if messages %}
        {% for msg in messages %}
          <h6 id="red">{{msg.message}}</h6>
        {% endfor %}
      {% endif %}
      <div class="reg">
        <form action="/register" method="post">
        {% csrf_token %}
          <fieldset>
            <legend><h3>Register</h3></legend>
            <p>Name: <input type="text" name="name"></p>
            <p>Alias: <input type="text" name="alias"></p>
            <p>Email: <input type="text" name="email"></p>
            <p>Password: <input type="text" name="password"></p>
            <p>Confirm Password: <input type="text" name="confpass"></p>
            <p><input type="submit" value="Register"></p>
        </fieldset>
        </form>
      </div>

      <div class="log">
        <form action="/login" method="post">
        {% csrf_token %}
          <fieldset>
            <legend><h3>Login</h3></legend>
            <p>Email: <input type="text" name="email"></p>
            <p>Password: <input type="password" name="password"></p>
            <p><input type="submit" value="Login"></p>
          </fieldset>
        </form>

      </div>
    </body>
</html>

apps/belt_review/templates/belt_review/users.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Users</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'belt_review/css/styles.css' %}"media="screen" title="no title"  charset="utf-8">
  </head>
  <body>
    <a href="/home"><button>Home</button></a>
    <a href="/add"><button>Add Book and Review</button></a>
    <a href="/logout"><button>Logout</button></a>

    <h2>User Alias: {{user.alias}}</h2>
    <h3>Name: {{user.name}}</h3>
    <h3>Email: {{user.email}}</h3>
    <h3>Total reviews: {{rating}}</h3>
    <h3>Posted Reviews on the following books:</h3>
    <!-- forloop -->
    <div class="scroll">
    {% for review in user.review_set.all %}

    <p><a href="/books/{{review.book.id}}">{{review.book.title}}</a></p>
    {% endfor %}
    </div>



  </body>
</html>